import {readFileSync,writeFileSync,mkdirSync} from "node:fs";
import {resolve} from "node:path";
const out=resolve("reports/value-update");
mkdirSync(out,{recursive:true});
const readJson=(path:string)=>JSON.parse(readFileSync(path,"utf8"));
const published=readJson(`${out}/published-version.json`);
const candidate=readJson("dist/build-info.json");
const readiness=readJson(`${out}/capabilities.json`);
const history=readJson(`${out}/history.json`);
const events=[5,15].map(i=>readJson(`${out}/event-${i}.json`));
const escape=(v:unknown)=>String(v??"Not available").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const pct=(v:number|null)=>v==null?"Unavailable":`${(v*100).toFixed(1)}%`;
const num=(v:number|null,digits=3)=>v==null?"Unavailable":v.toFixed(digits);
const image=(file:string,title:string)=>`<figure><img src="data:image/jpeg;base64,${readFileSync(`${out}/${file}`).toString("base64")}" alt="${escape(title)}"><figcaption>${escape(title)}</figcaption></figure>`;
const m=history.metrics;
const reconciled=Object.values(m.topLevelOutcomes).reduce((n:number,v)=>n+Number(v),0);
const timing=(e:any)=>e.prospective.timingGainSeconds??e.prospective.timingGain??e.prospective;
const tests=readFileSync("/tmp/value-update-full-tests.log","utf8");
const fullTests=tests.match(/# tests (\d+)[\s\S]*# pass (\d+)[\s\S]*# fail (\d+)[\s\S]*# skipped (\d+)/);
const finalTests=readFileSync("/tmp/value-update-targeted-tests.log","utf8");
const finalCounts=finalTests.match(/# tests (\d+)[\s\S]*# pass (\d+)[\s\S]*# fail (\d+)[\s\S]*# skipped (\d+)/);
const checks=readFileSync("/tmp/value-update-check-build.log","utf8");
const bundle={capturedAt:new Date().toISOString(),published,candidate,readiness,history,
  event5:events[0],event15:events[1],
  verification:{fullIsolated:fullTests?.slice(1),finalTargeted:finalCounts?.slice(1),
    typeCheckAndBuild:!checks.includes("error TS")&&checks.includes("dist/index.mjs"),
    signedInOwnerWorkflow:"NOT_VERIFIED",mainnetFundingPermissionsRecovery:"NOT_VERIFIED",
    browserAutomation:"Unavailable: testing worker kind was rejected by runtime. No authentication bypass added.",
    screenshots:"Actual running development app. Agent screenshots are signed out; no real owner signature."}};
writeFileSync(`${out}/evidence.json`,JSON.stringify(bundle,null,2));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bluewater value-aware update — delivery evidence</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#08161c;color:#dde8df;font:15px/1.55 system-ui,sans-serif}main{max-width:1140px;margin:auto;padding:36px 24px}h1{font-size:34px;line-height:1.15}h2{margin-top:32px;color:#c2dfa7}h3{font-size:17px}section{padding:20px;border:1px solid #294047;background:#11252c;margin:18px 0}code,pre{font:12px/1.5 monospace;overflow-wrap:anywhere}pre{white-space:pre-wrap;max-height:540px;overflow:auto;background:#07181d;padding:14px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:9px;border-bottom:1px solid #294047;text-align:left;overflow-wrap:anywhere}.scroll{overflow-x:auto}th{color:#bbd99f}.warning{border-left:4px solid #d8ad72}small,.muted,figcaption{color:#a6b8ae}figure{margin:20px 0}img{max-width:100%;display:block;border:1px solid #294047}figcaption{margin-top:7px}.phones{display:grid;grid-template-columns:1fr 1fr;gap:20px}.phones img{max-width:320px}summary{cursor:pointer;color:#c2dfa7}li{margin:8px 0}@media(max-width:700px){main{padding:20px 14px}.phones{grid-template-columns:1fr}}</style>
<main><p class="muted">BLUEWATERAI / CANDIDATE UPDATE EVIDENCE</p><h1>Value-aware research, clearer History, one owner setup path</h1><p>Captured ${escape(bundle.capturedAt)}. Development evidence is not production acceptance or trading permission.</p>
<section class="warning"><h2>Not live, not published</h2><p>This candidate was not published and no paid infrastructure was activated. Active research strategy: <code>waterx-qualification-gates-v3</code>. Event strategy: <code>waterx-event-lock-v1</code>, shadow-only, unchanged qualification thresholds. Economically learned stopping is <b>not qualified or released</b>.</p><p>${escape(readiness.readiness.blocker)} ${escape(readiness.readiness.nextAction)}</p><p>Owner setup signing is available only after mainnet identity checks, authenticated ownership, reviewed checked simulation and explicit wallet approval. Funding or logging in never starts trading.</p></section>
<h2>Build identities</h2><section><p>Published: <code>${escape(published.build.id)}</code></p><p>Published source commit: <code>${escape(published.build.sourceCommit)}</code></p><p>Candidate: <code>${escape(candidate.id)}</code></p><p>Candidate source snapshot: <code>${escape(candidate.sourceSnapshotSha256)}</code>; source archive SHA-256: <code>${escape(candidate.sourceArchiveSha256)}</code>.</p><p>Candidate source commit: ${candidate.sourceCommit===null?"Unavailable — dirty workspace, no invented commit":escape(candidate.sourceCommit)}. Production parity is not claimed.</p></section>
<h2>What changed</h2><ul><li>Live Desk design preserved. Accepted observations retain entry-value evidence alongside separate forecast, market and execution provenance.</li><li>$5 collateral defaults to a $6 minimum / $7 preferred total winning return before costs, editable in reviewed session settings. $7 is not a maximum. This preference does not change active research qualification.</li><li>Verified-quote accounting supports actual winning/losing payouts, fees counted once, gas valuation, full size, expiry, partial-fill behavior and enforceable limits. Indicative asks show gross illustrations only; net, expected edge and actual P/L stay unknown.</li><li>History is the primary filtered scorecard, with compact expandable rows. Legacy records and heavy gate diagnostics load separately on expansion.</li><li>Public paper capital, simulated counters/ledger and shadow-start controls removed; internal historical simulation records remain unchanged.</li><li>Owner setup and session review share a single guided route. Supported explicit owner actions use wallet-standard Slush transaction signing. An uncertain digest is retained for confirmation-only retries; a transport cancellation never automatically resubmits.</li></ul>
<h2>History denominators reconcile</h2><section><p>Cohort: ${escape(history.cohort.interval)} intervals, ${escape(history.cohort.strategy)}, ${escape(history.cohort.window)}, timezone offset ${escape(history.cohort.timezoneOffsetMinutes)} minutes. Captured as of ${escape(new Date(history.asOfMs).toISOString())}. All-strategy totals count strategy-rounds, not independent physical rounds.</p>
<p><b>${m.correct} : ${m.incorrect}</b> correct/incorrect; accuracy ${pct(m.hitRate)} on ${m.settledN} scored locks. Pending and disputed are excluded.</p>
<p>Committed decision coverage ${m.locks} / ${m.cohortN} = ${pct(m.choiceCoverage)}. Distinct data failures ${m.dataFailures} / ${m.cohortN} = ${pct(m.dataFailureRate)}.</p>
<p>Known expired discovered rounds without a decision: ${m.missingRecords} / ${m.cohortN} = ${pct(m.discoveredMissingRecordRate)}. Independently expected-slot denominator is unverified, so the expected missing-record rate remains <b>unavailable</b>. No provider IDs or independent expected slots were fabricated. Current unfinalized rounds are pending, not retrospectively declared missing.</p>
<p>Median lock elapsed ${num(m.medianElapsedMs/1000,1)}s; p90 ${num(m.p90ElapsedMs/1000,1)}s. These are elapsed decision times, not verified cross-machine transport latency.</p>
<div class="scroll"><table><tr><th>Mutually exclusive outcome</th><th>Strategy-round count</th></tr>${Object.entries(m.topLevelOutcomes).map(([k,v])=>`<tr><td>${escape(k)}</td><td>${escape(v)}</td></tr>`).join("")}<tr><th>Total</th><th>${reconciled} / ${m.cohortN} ${reconciled===m.cohortN?"— reconciled":"— MISMATCH"}</th></tr></table></div><p>Provider, scheduler and storage causes are overlapping diagnostics, never additional top-level outcomes. Missing causes are not assumed to be storage failures.</p></section>
<h2>Prospective matched event comparison</h2><p>Only prospectively captured exact rounds with verified settlements score. These small descriptive market-probability samples do not qualify an independent model or justify promotion.</p>
<div class="scroll"><table><tr><th>Interval</th><th>Discovered cohort</th><th>Event locks / cohort</th><th>Gate locks / cohort</th><th>Matched scored n</th><th>Matched event accuracy / Brier</th><th>Matched gate accuracy / Brier</th></tr>${events.map(e=>`<tr><td>${e.interval}m</td><td>${e.prospective.cohortN}</td><td>${e.prospective.event.locks} / ${e.prospective.cohortN}</td><td>${e.prospective.benchmark.locks} / ${e.prospective.cohortN}</td><td>${e.prospective.matchedN}</td><td>${pct(e.prospective.matchedEvent.accuracy)} / ${num(e.prospective.matchedEvent.brier,6)}</td><td>${pct(e.prospective.matchedBenchmark.accuracy)} / ${num(e.prospective.matchedBenchmark.brier,6)}</td></tr>`).join("")}</table></div>
${events.map(e=>`<details><summary>${e.interval}m timing, coverage and missing-data evidence</summary><pre>${escape(JSON.stringify(e.prospective,null,2))}</pre></details>`).join("")}
<section><h3>Entry economics and learning limits</h3><p>Both intervals have zero verified full-size quotes and zero qualified calibrated EV records in this comparison. Quote-adjusted expected profit, realized trading P/L and drawdown are unavailable; no assumed fill is substituted. Archived indicative asks are recovered only from the selected frozen observation available at decision time.</p><p>Separate 5m/15m timing/error learners retain whole trajectories, overlap-aware chronological fitting/calibration/policy/test partitions and selected-subset calibration. Economic training readiness separately requires verified compatible full-size terms. It is not a completed economic stopping artifact.</p>${events.map(e=>`<details><summary>${e.interval}m training deficits and economic readiness</summary><pre>${escape(JSON.stringify(e.training?.report??e.training,null,2))}</pre></details>`).join("")}</section>
<h2>Latency and production operation</h2><p>Collection/discovery, queue, evaluation, database acquisition/preparation/final transaction and acknowledgement are separately instrumented. Browser delivery is not established by server timestamps. Monotonic process samples are not an uptime SLA. Published hosting remains Autoscale; the protected, independent production collector has not been activated. A current isolated restore and an approved cost quote remain prerequisites.</p>
<details><summary>Development process latency evidence</summary><pre>${escape(JSON.stringify(events[0].latency,null,2))}</pre></details>
<h2>Live-execution readiness checklist</h2><section><p><b>IMPLEMENTED means software exists, not an on-chain proof or release approval.</b> No complete signed-in mainnet desktop/mobile flow was verified. Wallet-standard signing was unit-tested with synthetic wallet features; no real Slush signature, funded placement or recovery was executed.</p>${readiness.readiness.items.map((i:any)=>`<h3>${escape(i.label)} — ${escape(i.status)}</h3><p>${escape(i.evidence)}</p><p class="muted">Next: ${escape(i.nextAction)}</p>`).join("")}<h3>Required owner interactions</h3><ul>${readiness.readiness.ownerInteractions.map((s:string)=>`<li>${escape(s)}</li>`).join("")}</ul><h3>Autonomous only after release and finite owner approval</h3><ul>${readiness.readiness.autonomousWhenReleased.map((s:string)=>`<li>${escape(s)}</li>`).join("")}</ul></section>
<h2>Verification</h2><p>Complete isolated suite: ${fullTests?.[2]??"unavailable"} passed / ${fullTests?.[1]??"unavailable"} tests; ${fullTests?.[3]??"unavailable"} failed, ${fullTests?.[4]??"unavailable"} skipped. Final targeted post-refinement suite: ${finalCounts?.[2]??"unavailable"} passed / ${finalCounts?.[1]??"unavailable"}; ${finalCounts?.[3]??"unavailable"} failed. Type check and candidate production build passed.</p><p>The available browser automation callback rejected the testing worker kind. Signed-in UI therefore remains unverified. No temporary login bypass was added. Screenshots below show the actual running development app; Agent captures are signed out.</p>
<h2>Desktop and phone screenshots</h2>${image("history-desktop.jpg","Actual History desktop — filtered cohort and compact evidence rows")}${image("agent-desktop.jpg","Actual Agent desktop — guided owner setup; signed out")}
<div class="phones">${image("history-phone.jpg","History, 320px wide; tall capture shows summary and rows")}${image("agent-phone.jpg","Agent, 320×720; signed out")}</div>
<section class="warning"><h2>Explicitly incomplete</h2><ul><li>Authoritative event-policy promotion and economically trained stopping: not completed or qualified.</li><li>Independent expected-round slot reconciliation: unverified; expected-cohort percentages remain unavailable.</li><li>Durable production collection/latency recovery: not activated or accepted; published storage failures remain unresolved.</li><li>Operator-only signer administration, effective restricted permissions, credited funding, final dispatch, aggregate reservations, uncertain autonomous orders, fills/settlement and funded recovery: not end-to-end verified.</li><li>Actual owner-signed desktop/mobile Slush workflow: not verified without an owner-controlled wallet and approved bounded operation.</li></ul><p>No successful build, connection, simulation or synthetic signature is called live.</p></section></main></html>`;
writeFileSync(`${out}/delivery-evidence.html`,html);
console.log(JSON.stringify({report:`${out}/delivery-evidence.html`,cohortN:m.cohortN,reconciled,candidateId:candidate.id,fullIsolated:fullTests?.slice(1),finalTargeted:finalCounts?.slice(1)},null,2));
